import { createSlice } from "@reduxjs/toolkit";
import { IState, ISequencerState } from "./../../app/types";
import { playAllSteps } from "./Sequencer.functions";

export const sequencerSlice = createSlice({
  name: "sequencer",
  initialState: {
    sequence: [
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
      {
        kick: false,
        hihat: false,
        hihat_o: false,
        snare_1: false,
        snare_2: false,
        tom_1: false,
        tom_2: false,
        ride: false,
        crash: false,
        footstep: false,
        snowball: false,
        bottlepick: false,
      },
    ],
  },
  reducers: {
    playSequence: (state: ISequencerState) => {
      playAllSteps(state, 130);
    },

    toggleHit: (state: ISequencerState, action) => {
      // na kliknięcie obecny stan zmieniamy na odwrotny
      let step = action.payload.step;
      let sound = action.payload.sound;

      state.sequence[step][sound] = !state.sequence[step][sound];
    },
  },
});

export const { playSequence, toggleHit } = sequencerSlice.actions;

export const sequenceSelector = (state: IState) => state.sequencer.sequence;

export default sequencerSlice.reducer;
